version: '3.8'
services:
    nginx:
        image: nginx:1.18-alpine
        ports:
            - '8080:80'
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        links:
            - php-fpm
        depends_on:
            - php-fpm
        networks:
            default:
    php-fpm:
        image: 'bitnami/php-fpm:latest'
        volumes:
            - .:/var/www
            - ./docker/php-fpm/conf.d:/opt/bitnami/php/etc/conf.d
            - ./docker/php-fpm/sessions:/opt/bitnami/php/sessions
            - ./docker/php-fpm/logs:/opt/bitnami/php/logs
            - ./docker/php-fpm/logs:/bitnami/php-fpm/logs
        restart: 'always'
        networks:
            default:
                aliases:
                    - 'php-fpm'
    db:
        image: mysql:8.0
        ports:
            - '3306:3306'
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: lostseas
            MYSQL_USER: lostseas
            MYSQL_PASSWORD: lostseas
            MYSQL_ROOT_PASSWORD: toor
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: lostseas
            MYSQL_PASSWORD: lostseas
            MYSQL_ROOT_PASSWORD: toor
volumes:
    persistent:
