<?php

const FOOD_BUY_PRICE = 16;
const FOOD_SELL_PRICE = 11;
const WATER_BUY_PRICE = 12;
const WATER_SELL_PRICE = 8;
const PORCELAIN_BUY_PRICE = 35;
const PORCELAIN_SELL_PRICE = 24;
const SPICES_BUY_PRICE = 20;
const SPICES_SELL_PRICE = 14;
const SILK_BUY_PRICE = 45;
const SILK_SELL_PRICE = 31;
const MEDICINE_BUY_PRICE = 40;
const MEDICINE_SELL_PRICE = 28;
const TOBACCO_BUY_PRICE = 75;
const TOBACCO_SELL_PRICE = 52;
const RUM_BUY_PRICE = 150;
const RUM_SELL_PRICE = 105;
