<?php

const DINNER_BUY_PRICE = 25;
const TOBACCO_BUY_PRICE = 30;
const WINE_BUY_PRICE = 50;
const RUM_BUY_PRICE = 70;

// Out of 10
const SAILORS_JOIN_CHANCE_MIN = 5;
const SAILORS_FIGHT_AND_YOU_WIN_CHANCE_MIN = 8;
const SAILORS_FIGHT_AND_YOU_LOOSE_CHANCE_MIN = 10;

const SAILORS_WIN_LOOT_MIN = 10;
const SAILORS_WIN_LOOT_MAX = 100;

const SAILORS_LOOSE_HEALTH_DECREASE_MIN = 10;
const SAILORS_LOOSE_HEALTH_DECREASE_MAX = 30;

// Out of 40
const GAMBLE_WIN_JACKPOT_CHANCE = 1;
const GAMBLE_WIN_CHANCE = 7;

// Times bet value
const GAMBLE_WIN_MIN_PROFIT = 2;
const GAMBLE_WIN_MAX_PROFIT = 5;
const GAMBLE_WIN_JACKPOT_PROFIT = 20;
